services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./debug:/app/debug
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/quatro_gnc
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY= mCzMpq_2bYpozbn2q6RFfgaA1cyG5-DWCc3ImJkTl7g
      - DEFAULT_ADMIN_USER=taller_admin
      - DEFAULT_ADMIN_PASSWORD=taller_admin_password
      - RPA_HEADLESS=true
      - GUNICORN_CMD_ARGS=--timeout 120 --keep-alive 5 --access-logfile - --error-logfile -
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: ["python", "worker.py"]
    volumes:
      - ./debug:/app/debug
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/quatro_gnc
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY= mCzMpq_2bYpozbn2q6RFfgaA1cyG5-DWCc3ImJkTl7g
      - DEFAULT_ADMIN_USER=taller_admin
      - DEFAULT_ADMIN_PASSWORD=taller_admin_password
      - RPA_HEADLESS=true
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quatro_gnc
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  postgres_data:
